<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>NotumHUD</RootNamespace>
    <Platforms>AnyCPU;x86</Platforms>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AOSharp.Common">
      <HintPath>..\NotumHUD\packages\AOSharp.Common.dll</HintPath>
    </Reference>
    <Reference Include="AOSharp.Core">
      <HintPath>..\NotumHUD\packages\AOSharp.Core.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>PATH_TO_NEWTONSOFT\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="UI\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UI\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
  </ItemGroup>
</Project>